using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace AwesomeSnippets {
    public static class ScriptTemplatesMenuItemGenerator {
        public const string AssetPath_Default = "Editor/";
        public const string Name_Generate_Class = "ScriptTemplatesMenuItems";
        public const string Name_Generate_File = Name_Generate_Class + ".cs";

        private const string Header =
            "//auto generated by ScriptTemplatesMenuItemGenerator.cs\n" +
            "\n" +
            "using UnityEditor;\n" +
            "using UnityEngine;\n" +
            "\n" +
            "namespace AwesomeSnippets {\n" +
            "\n" +
            "\t[InitializeOnLoad]\n" +
            "\tpublic static class ##CLASSNAME## {\n" +
            "\t\tprivate static ScriptTemplatesSettings settings;\n" +
            "\n" +
            "\t\tstatic ##CLASSNAME##() {\n" +
            "\t\t\tstring[] vs = AssetDatabase.FindAssets(\"t:ScriptTemplatesSettings\");\n" +
            "\n" +
            "\t\t\tif (vs.Length > 0) {\n" +
            "\t\t\t\tsettings = AssetDatabase.LoadAssetAtPath<ScriptTemplatesSettings>(AssetDatabase.GUIDToAssetPath(vs[0]));\n" +
            "\t\t\t} else {\n" +
            "\t\t\t\tDebug.LogWarning(\"[ScriptTemplates] ScriptTemplatesSettings Not Found\");\n" +
            "\t\t\t}\n" +
            "\t\t}\n";

        private const string Function =
            "\n" +
            "\t\t[MenuItem(\"##MENUPATH####SCRIPTNAME##\", false, 80)]\n" +
            "\t\tprivate static void CreateScript##SCRIPTNAMETRIM##() {\n" +
            "\t\t\tif (settings.Templates[##INDEX##]) {\n" +
            "\t\t\t\tstring templatePath = AssetDatabase.GetAssetPath(settings.Templates[##INDEX##]);\n" +
            "\t\t\t\tProjectWindowUtil.CreateScriptAssetFromTemplateFile(templatePath, \"##SCRIPTNAMETRIM##.cs\");\n" +
            "\t\t\t}\n" +
            "\t\t}\n" +
            "\n";

        private const string Footer =
            "\t}\n" +
            "}";

        public static void GenerateMenuItemScript(ScriptTemplatesSettings settings) {
            string menuItemPath = "Assets/Create/";
            if (settings.Templates.Count > 1) {
                menuItemPath = "Assets/Create/C# Script Templates/";
            }

            //HEADER
            StringBuilder stringBuilder = new StringBuilder();
            string strHeader = Header.Replace("##CLASSNAME##", Name_Generate_Class);
            stringBuilder.Append(strHeader);

            //BODY
            List<string> usedName = new List<string>();
            for (int loop = 0; loop < settings.Templates.Count; loop++) {
                TextAsset textAsset = settings.Templates[loop];
                if (textAsset != null) {
                    string assetName = textAsset.name;
                    if (usedName.Contains(assetName)) {
                        assetName += loop;
                    } else {
                        usedName.Add(assetName);
                    }

                    string strFunction = Function
                        .Replace("##SCRIPTNAME##", assetName)
                        .Replace("##SCRIPTNAMETRIM##", assetName.Replace(" ", ""))
                        .Replace("##MENUPATH##", menuItemPath)
                        .Replace("##INDEX##", loop.ToString());

                    stringBuilder.Append(strFunction);
                }
            }

            //FOOTER
            stringBuilder.Append(Footer);

            DirectoryInfo directoryInfo = ScriptTemplatesWindow.FindWindowScriptAssetDirectory();
            if (directoryInfo != null) {
                try {
                    File.WriteAllText(directoryInfo.FullName + "\\" + Name_Generate_File, stringBuilder.ToString());

                    AssetDatabase.ImportAsset(directoryInfo + "\\" + Name_Generate_File);
                    TextAsset textAsset =
                        AssetDatabase.LoadAssetAtPath<TextAsset>(directoryInfo + "\\" + Name_Generate_File);
                    AssetDatabase.SetLabels(textAsset, new[] { ScriptTemplatesWindow.Label_AwesomeSnippets });

                    Debug.Log("Templates Updated");
                } catch (DirectoryNotFoundException e) {
                    Debug.LogException(e);
                }
            }
        }
    }
}