//auto generated by ScriptTemplatesMenuItemGenerator.cs

using UnityEditor;
using UnityEngine;

namespace AwesomeSnippets {

	[InitializeOnLoad]
	public static class ScriptTemplatesMenuItems {
		private static ScriptTemplatesSettings settings;

		static ScriptTemplatesMenuItems() {
			string[] vs = AssetDatabase.FindAssets("t:ScriptTemplatesSettings");

			if (vs.Length > 0) {
				settings = AssetDatabase.LoadAssetAtPath<ScriptTemplatesSettings>(AssetDatabase.GUIDToAssetPath(vs[0]));
			} else {
				Debug.LogWarning("[ScriptTemplates] ScriptTemplatesSettings Not Found");
			}
		}

		[MenuItem("Assets/Create/ScriptTemplateSample", false, 80)]
		private static void CreateScriptScriptTemplateSample() {
			if (settings.Templates[0]) {
				string templatePath = AssetDatabase.GetAssetPath(settings.Templates[0]);
				ProjectWindowUtil.CreateScriptAssetFromTemplateFile(templatePath, "ScriptTemplateSample.cs");
			}
		}

	}
}